### 1. Register DBlocker
POST http://localhost:8080/api/dblockers
Content-Type: application/json

{
    "name": "SCM TEST",
    "serial_numb": "250000",
    "ip": "10.88.81.100",
    "latitude": -7.786959801210232,
    "longitude": 110.4220920495705,
    "desc": "Drone blocker di SCM",
    "angle_start": 0
}

# {
#     "name": "Edu Park IMIP",
#     "serial_numb": "250002",
#     "ip": "10.88.81.3",
#     "latitude": -7.788432918834558,
#     "longitude": 110.44306970000933,
#     "desc": "Drone blocker di edu park",
#     "angle_start": 0
# }

# {
#     "name": "Runway 13 Bandara",
#     "serial_numb": "250001",
#     "ip": "10.88.81.2",
#     "latitude": -7.786959801210232,
#     "longitude": 110.4220920495705,
#     "desc": "Drone blocker di barat",
#     "angle_start": 0
# }

### 2. Get All DBlockers
GET http://localhost:8080/api/dblockers

### 3. Get DBlocker by ID
GET http://localhost:8080/api/dblockers/1

### 4. Update DBlocker by ID
PUT http://localhost:8080/api/dblockers/1
Content-Type: application/json

{
    "name": "Runway 13 Bandara",
    "serial_numb": "250001",
    "ip": "10.88.81.2",
    "latitude": -7.786959801210232,
    "longitude": 110.4220920495705,
    "desc": "Drone blocker di barat",
    "angle_start": 0,
    "config": [
        {"signal_ctrl": true, "signal_gps": false},
        {"signal_ctrl": true, "signal_gps": false},
        {"signal_ctrl": true, "signal_gps": false},
        {"signal_ctrl": false, "signal_gps": true},
        {"signal_ctrl": false, "signal_gps": true},
        {"signal_ctrl": false, "signal_gps": true}
    ]
}


### 5. Delete DBlocker by ID
DELETE http://localhost:8080/api/dblockers/1


### 6. Update DBlocker Config
PUT http://localhost:8080/api/dblockers/config
Content-Type: application/json

{
    "id": 4,
    "config": [
        {"signal_ctrl": true, "signal_gps": false},
        {"signal_ctrl": true, "signal_gps": false},
        {"signal_ctrl": true, "signal_gps": false},
        {"signal_ctrl": false, "signal_gps": true},
        {"signal_ctrl": false, "signal_gps": true},
        {"signal_ctrl": false, "signal_gps": true}
    ]
}