### 1. Register DBlocker
POST http://10.88.81.16:8080/api/dblockers
Content-Type: application/json

# {
#     "name": "SCM TEST",
#     "serial_numb": "250000",
#     "ip": "10.88.81.100",
#     "latitude": -7.786959801210232,
#     "longitude": 110.4220920495705,
#     "desc": "Drone blocker di SCM",
#     "angle_start": 0
# }

{
    "name": "05 Terminal Utara Tsingshan",
    "serial_numb": "250005",
    "ip": "10.88.81.6",
    "latitude": -7.767097914728923,
    "longitude": 110.43166037380772,
    "desc": "Drone blocker di bandara",
    "angle_start": 0
}

# {
#     "name": "Runway 13 Bandara",
#     "serial_numb": "250001",
#     "ip": "10.88.81.2",
#     "latitude": -7.786959801210232,
#     "longitude": 110.4220920495705,
#     "desc": "Drone blocker di barat",
#     "angle_start": 0
# }

### 2. Get All DBlockers
GET http://10.88.81.16:8080/api/dblockers

### 3. Get DBlocker by ID
GET http://localhost:8080/api/dblockers/1

### 4. Update DBlocker by ID
PUT http://localhost:8080/api/dblockers/1
Content-Type: application/json

{
    "name": "Runway 13 Bandara",
    "serial_numb": "250001",
    "ip": "10.88.81.2",
    "latitude": -7.786959801210232,
    "longitude": 110.4220920495705,
    "desc": "Drone blocker di barat",
    "angle_start": 0,
    "config": [
        {"signal_ctrl": true, "signal_gps": false},
        {"signal_ctrl": true, "signal_gps": false},
        {"signal_ctrl": true, "signal_gps": false},
        {"signal_ctrl": false, "signal_gps": true},
        {"signal_ctrl": false, "signal_gps": true},
        {"signal_ctrl": false, "signal_gps": true}
    ]
}


### 5. Delete DBlocker by ID
DELETE http://10.88.81.16:8080/api/dblockers/2


### 6. Update DBlocker Config
PUT http://localhost:8080/api/dblockers/config
Content-Type: application/json

{
    "id": 4,
    "config": [
        {"signal_ctrl": true, "signal_gps": false},
        {"signal_ctrl": true, "signal_gps": false},
        {"signal_ctrl": true, "signal_gps": false},
        {"signal_ctrl": false, "signal_gps": true},
        {"signal_ctrl": false, "signal_gps": true},
        {"signal_ctrl": false, "signal_gps": true}
    ]
}

### 7. Turn Off All DBlocker Config
GET http://192.168.1.174:8080/api/dblockers/config/off/3

### 7. Turn Off All DBlocker Config B
GET http://10.88.81.16:8080/api/dblockers/config/off/5