# @host = http://10.88.81.16:8080
@host = http://localhost:8080

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODA4NDY5MDQsImlzX2FkbWluIjp0cnVlLCJ1c2VyX2lkIjo2LCJ1c2VybmFtZSI6ImFqaSJ9.TCqZ5wHs7XaPLMPNeq8UHFf_o9u9WKdjO0VsRNikFe4

#############################
# DRONE DETECTORS
#############################

### 10. Register Detector 1 (Runway 13 Bandara)
POST {{host}}/api/detectors
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Detector1",
    "latitude": -2.81968,
    "longitude": 122.15309,
    "host": "10.88.81.15",
    "port": 5555
}

### 11. Register Detector 2 (Terminal Tsingsan)
POST {{host}}/api/detectors
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Detector 2",
    "latitude": -2.809000,
    "longitude": 122.148000,
    "host": "localhost",
    "port": 5555
}

### 12. Get All Detectors
GET {{host}}/api/detectors
Authorization: Bearer {{token}}

### 13. Update Detector
PUT {{host}}/api/detectors/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Detector2",
      "latitude": -2.855106,
      "longitude": 122.182216,
      "host": "10.88.81.14",
    "port": 5555
}

### 14. Delete Detector
DELETE {{host}}/api/detectors/1
Authorization: Bearer {{token}}

#############################
# DRONE EVENTS
#############################

### 15. Get Recent Drone Events (all detectors)
GET {{host}}/api/drone-events?limit=50
Authorization: Bearer {{token}}

### 16. Get Drone Events by Detector ID
GET {{host}}/api/drone-events?detector_id=1&limit=50
Authorization: Bearer {{token}}

### 17. Get Drone Events by Date
GET {{host}}/api/drone-events?from=2026-04-01&to=2026-04-07&limit=100
Authorization: Bearer {{token}}

### 18. Delete Drone Events by Date Range
DELETE {{host}}/api/drone-events?from=2026-04-01&to=2026-04-07
Authorization: Bearer {{token}}
