services:
  app:
    container_name: dblocker-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
      - mosquitto
    environment:
      APP_PORT: ${APP_PORT:-8080}
      MQTT_BROKER: ${MQTT_BROKER:-tcp://mosquitto:1883}
      MQTT_USERNAME: ${MQTT_USERNAME:-DBL0KER}
      MQTT_PASSWORD: ${MQTT_PASSWORD:-mysecretmqttpassword}
      DB_HOST: ${DB_HOST:-postgres}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:-scm}
      DB_PASSWORD: ${DB_PASSWORD:-mysecretpassword}
      DB_NAME: ${DB_NAME:-dblocker-db}
      DB_SSLMODE: ${DB_SSLMODE:-disable}
      DB_TIMEZONE: ${DB_TIMEZONE:-UTC}
      JWT_SECRET: ${JWT_SECRET:-}
      API_KEY: ${API_KEY:-}
      ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin}
    ports:
      - "8080:8080"

  assist:
    container_name: dblocker-assist-app
    build:
      context: .
      dockerfile: Dockerfile.assist
    restart: unless-stopped
    depends_on:
      - app
    environment:
      API_KEY: ${API_KEY:-}
      BACKEND_URL: http://dblocker-app:8080
      DRONE_DETECTORS: ${DRONE_DETECTORS:-}

  mosquitto:
    container_name: dblocker-mqtt
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - "${MQTT_PUBLIC_PORT:-1883}:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  postgres:
    container_name: dblocker-postgres
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-scm}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-mysecretpassword}
      POSTGRES_DB: ${DB_NAME:-dblocker-db}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: